import { describe, expect, it } from 'vitest';
import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { engineGroups, getAllEngineFeatures, getEngineGroup } from '@/data/admin/engines.catalog';
import { enginesData } from '@/data/admin/engines.data';

const root = process.cwd();

const REQUIRED_USER_FEATURES = [
  'Automation engine',
  'Workflow builder',
  'Event triggers',
  'Condition builder',
  'Action builder',
  'Scheduled workflows',
  'Event-based workflows',
  'Customer workflows',
  'Billing workflows',
  'Network workflows',
  'Support workflows',
  'Employee workflows',
  'Notification workflows',
  'Workflow execution logs',
  'Workflow retry mechanism',
  'Workflow failure handling',
  'Workflow templates',
  'Workflow enable/disable',
  'Workflow execution history',
  'Service provisioning',
  'Automatic provisioning',
  'Service deprovisioning',
  'Service reprovisioning',
  'Provisioning templates',
  'Provisioning queue',
  'Provisioning status',
  'Provisioning retry',
  'Provisioning failure handling',
  'Provisioning logs',
  'Bulk provisioning',
  'Device configuration templates',
  'Package-to-network-policy mapping',
  'Automatic RADIUS provisioning',
  'Automatic MikroTik provisioning',
  'Automatic IP allocation',
  'Automatic VLAN assignment',
  'Automatic ONU provisioning',
  'Network event engine',
  'Alert rules',
  'Threshold rules',
  'Router-down detection',
  'OLT-down detection',
  'ONU LOS detection',
  'Interface-down detection',
  'High CPU alert',
  'High memory alert',
  'High bandwidth alert',
  'Packet-loss alert',
  'Latency alert',
  'Jitter monitoring',
  'Link-flapping detection',
  'Alert deduplication',
  'Alert acknowledgment',
  'Alert escalation',
  'Alert suppression',
  'Maintenance windows',
  'Incident management',
  'Incident timeline',
  'Network incident history',
  'Customer lifecycle management',
  'Lead-to-customer conversion',
  'Application workflow',
  'Customer verification workflow',
  'Installation workflow',
  'Activation workflow',
  'Temporary suspension',
  'Temporary service hold',
  'Reactivation workflow',
  'Cancellation workflow',
  'Customer archival',
  'Customer migration',
  'Customer merge',
  'Transfer between POPs',
  'Transfer between areas',
  'Transfer between resellers',
  'Installation requests',
  'Installation scheduling',
  'Installation calendar',
  'Installer assignment',
  'Installation checklist',
  'Installation materials tracking',
  'Installation fee management',
  'Installation photos',
  'Customer signature',
  'GPS verification',
  'ONU/ONT registration',
  'Installation completion',
  'Installation quality check',
  'Installation history',
  'General ledger',
  'Trial balance',
  'Accounts receivable',
  'Accounts payable',
  'Cash flow statement',
  'Profit & loss statement',
  'Bank reconciliation',
  'Fiscal year management',
  'Accounting periods',
  'Opening balances',
  'Closing entries',
  'Cost centers',
  'Branch accounting',
  'Payment settlement',
  'Tax/VAT ledger',
  'Financial audit trail',
  'Lead sources',
  'Lead scoring',
  'Lead assignment',
  'Follow-up reminders',
  'Sales activities',
  'Sales targets',
  'Sales commissions',
  'Customer segmentation',
  'Customer lifetime value',
  'Churn analysis',
  'Retention campaigns',
  'Win-back campaigns',
  'Customer journey timeline',
  'Customer interaction history',
  'REST API',
  'API versioning',
  'OAuth2',
  'API scopes',
  'API rate limiting',
  'API usage analytics',
  'API logs',
  'Webhook subscriptions',
  'Webhook event types',
  'Webhook retries',
  'Webhook failure handling',
  'Webhook signing',
  'Webhook delivery history',
  'Developer documentation',
  'API sandbox',
  'API test console',
  'Two-factor authentication',
  'Login history',
  'Device management',
  'Active session management',
  'Remote session termination',
  'IP allowlist',
  'IP blocklist',
  'Brute-force protection',
  'Rate limiting',
  'Security event logs',
  'Security alerts',
  'API-key rotation',
  'Webhook signature verification',
  'Sensitive-data encryption',
  'Security policy management',
  'Password policy',
  'Session timeout policy',
  'Suspicious-login detection',
  'Scheduled backups',
  'Incremental backups',
  'Backup retention policy',
  'Off-site backups',
  'Backup verification',
  'Restore testing',
  'Point-in-time recovery',
  'Disaster recovery configuration',
  'Disaster recovery status',
  'Database replication support',
  'Recovery audit logs',
  'Tenant feature flags',
  'Tenant feature limits',
  'Tenant customer quota',
  'Tenant storage quota',
  'Tenant API quota',
  'Tenant rate limits',
  'Tenant resource monitoring',
  'Tenant suspension rules',
  'Tenant data export',
  'Tenant data deletion',
  'Tenant migration',
  'Tenant backup',
  'Tenant restore',
  'Custom-domain verification',
  'Tenant environment configuration',
  'AI customer support',
  'AI ticket classification',
  'AI ticket response generation',
  'AI ticket summarization',
  'AI network diagnosis',
  'AI billing assistant',
  'AI sales assistant',
  'AI churn prediction',
  'AI fraud detection',
  'AI revenue forecasting',
  'AI package recommendation',
  'AI NOC assistant',
  'AI report generation',
  'AI natural-language analytics',
  'AI customer sentiment analysis',
  'AI knowledge-base assistant',
  'AI troubleshooting workflows',
  'AI usage analytics',
  'Customer service status page',
  'Personalized notifications',
  'Notification preferences',
  'Notification history',
  'Multi-channel notification preference',
  'Service request tracking',
  'Customer feedback',
  'CSAT rating',
  'NPS survey',
  'Complaint escalation',
  'Satisfaction analytics',
  'Serial-number tracking',
  'IMEI tracking',
  'Asset lifecycle',
  'Asset maintenance',
  'Asset warranty tracking',
  'Asset return',
  'Damaged-item management',
  'Lost-item management',
  'Stock adjustment',
  'Stock audit',
  'Low-stock alerts',
  'Reorder levels',
  'Purchase approval workflow',
  'Supplier payment tracking',
  'Reseller wallet',
  'Reseller credit limit',
  'Reseller billing',
  'Reseller invoice',
  'Reseller customer quota',
  'Reseller bandwidth quota',
  'Reseller package restrictions',
  'Reseller API',
  'Reseller commission rules',
  'Reseller commission settlement',
  'Reseller performance analytics',
  'Reseller statement',
  'SLA monitoring',
  'SLA violation detection',
  'Network capacity planning',
  'Bandwidth forecasting',
  'Interface utilization history',
  'Historical network performance',
  'Network topology discovery',
  'Automatic topology updates',
  'Device configuration backup',
  'Device configuration versioning',
  'Configuration rollback',
  'Firmware inventory',
  'Maintenance scheduling',
  'Network change management',
  'OLT port management',
  'PON management',
  'ONU lifecycle',
  'ONU replacement',
  'ONU relocation',
  'Fiber core management',
  'Fiber cable management',
  'Fiber route management',
  'Splitter management',
  'Splitter capacity',
  'Optical power history',
  'Optical degradation alerts',
  'Fiber fault management',
  'Fiber inventory',
  'Customer-to-OLT topology',
  'Customer-to-PON topology',
  'Billing cycle engine',
  'Custom billing cycles',
  'Billing calendar',
  'Automated invoice generation',
  'Invoice numbering rules',
  'Invoice templates',
  'Invoice delivery tracking',
  'Payment allocation rules',
  'Automatic payment matching',
  'Overpayment handling',
  'Underpayment handling',
  'Credit balance management',
  'Customer credit limits',
  'Billing dispute management',
  'Billing adjustment workflow',
  'Collection escalation',
  'Custom report builder',
  'Scheduled reports',
  'Report subscriptions',
  'Dashboard builder',
  'Custom KPI builder',
  'Revenue forecasting',
  'Customer growth analytics',
  'Customer churn analytics',
  'ARPU analytics',
  'MRR analytics',
  'Collection efficiency',
  'Package profitability',
  'POP profitability',
  'Reseller profitability',
  'Employee performance analytics',
  'Network profitability',
  'Cost analysis',
  'MRR',
  'ARR',
  'Churn rate',
  'Customer acquisition cost',
  'Lifetime value',
  'Average revenue per tenant',
  'Trial conversion rate',
  'Upgrade rate',
  'Downgrade rate',
  'Tenant retention',
  'Feature usage analytics',
  'Tenant health analytics',
  'Product usage analytics',
  'SaaS revenue forecasting',
] as const;

describe('ISP Engines suite completeness', () => {
  const features = getAllEngineFeatures();

  it('has exactly 20 engine groups', () => {
    expect(engineGroups).toHaveLength(20);
  });

  it('has 300+ features with unique ids and actions', () => {
    expect(features.length).toBeGreaterThanOrEqual(300);
    const ids = features.map((f) => f.id);
    expect(new Set(ids).size).toBe(ids.length);
    for (const f of features) {
      expect(f.actions.length).toBeGreaterThan(0);
      expect(f.name.length).toBeGreaterThan(0);
      expect(f.description.length).toBeGreaterThan(0);
    }
  });

  it('covers every required user-roadmap feature name', () => {
    const names = new Set(features.map((f) => f.name));
    const missing = REQUIRED_USER_FEATURES.filter((n) => !names.has(n));
    expect(missing, `missing features: ${missing.join(', ')}`).toEqual([]);
  });

  it('seeds dummy records and logs for every feature', () => {
    for (const f of features) {
      expect(
        enginesData.records.some((r) => r.featureId === f.id),
        `no records for ${f.id}`,
      ).toBe(true);
      expect(
        enginesData.logs.some((l) => l.featureId === f.id),
        `no logs for ${f.id}`,
      ).toBe(true);
    }
  });

  it('exposes summary counts consistent with data', () => {
    expect(enginesData.summary.groups).toBe(20);
    expect(enginesData.summary.features).toBe(features.length);
    expect(enginesData.summary.records).toBe(enginesData.records.length);
    expect(enginesData.summary.logs).toBe(enginesData.logs.length);
  });

  it('wires portal hubs and slice routes on disk', () => {
    for (const g of engineGroups) {
      expect(getEngineGroup(g.id)?.id).toBe(g.id);
      const base =
        g.portal === 'platform'
          ? `src/app/(portal)/platform/engines/${g.id}/page.tsx`
          : `src/app/(portal)/admin/engines/${g.id}/page.tsx`;
      expect(existsSync(join(root, base)), `missing route ${base}`).toBe(true);
    }
    expect(existsSync(join(root, 'src/app/(portal)/admin/engines/page.tsx'))).toBe(true);
    expect(existsSync(join(root, 'src/app/(portal)/platform/engines/page.tsx'))).toBe(true);
    expect(existsSync(join(root, 'src/app/(portal)/customer/experience/page.tsx'))).toBe(true);
    expect(existsSync(join(root, 'src/app/(portal)/employee/installations/page.tsx'))).toBe(true);
  });
});
