export const queryKeys = {
  auth: {
    me: ['auth', 'me'] as const,
  },
  customer: {
    dashboard: ['customer', 'dashboard'] as const,
    user: ['customer', 'user'] as const,
    usage: (period?: string) => ['customer', 'usage', period] as const,
    wifi: ['customer', 'wifi'] as const,
    tickets: (params?: Record<string, unknown>) => ['customer', 'tickets', params] as const,
    ticketDetail: (id: string | number) => ['customer', 'ticket', id] as const,
    ticketMessages: (id: string | number) => ['customer', 'ticket-messages', id] as const,
    subscriptions: ['customer', 'subscriptions'] as const,
    payments: (params?: Record<string, unknown>) => ['customer', 'payments', params] as const,
    rewards: ['customer', 'rewards'] as const,
    referral: ['customer', 'referral'] as const,
    announcements: ['customer', 'announcements'] as const,
  },
  admin: {
    dashboard: ['admin', 'dashboard'] as const,
    customers: (params?: Record<string, unknown>) => ['admin', 'customers', params] as const,
    customerDetail: (id: string | number) => ['admin', 'customer', id] as const,
    areas: (params?: Record<string, unknown>) => ['admin', 'areas', params] as const,
    areaDetail: (id: string | number) => ['admin', 'area', id] as const,
    subareas: (params?: Record<string, unknown>) => ['admin', 'subareas', params] as const,
    subareaDetail: (id: string | number) => ['admin', 'subarea', id] as const,
    payments: (params?: Record<string, unknown>) => ['admin', 'payments', params] as const,
    invoices: (params?: Record<string, unknown>) => ['admin', 'invoices', params] as const,
    resellers: (params?: Record<string, unknown>) => ['admin', 'resellers', params] as const,
    resellerDetail: (id: string | number) => ['admin', 'reseller', id] as const,
    employees: (params?: Record<string, unknown>) => ['admin', 'employees', params] as const,
    employeeDetail: (id: string | number) => ['admin', 'employee', id] as const,
    attendance: (params?: Record<string, unknown>) => ['admin', 'attendance', params] as const,
    salary: (params?: Record<string, unknown>) => ['admin', 'salary', params] as const,
    advanceLoans: (params?: Record<string, unknown>) => ['admin', 'advance-loans', params] as const,
    tickets: (params?: Record<string, unknown>) => ['admin', 'tickets', params] as const,
    ticketDetail: (id: string | number) => ['admin', 'ticket', id] as const,
    ticketMessages: (id: string | number) => ['admin', 'ticket-messages', id] as const,
    smsTemplates: ['admin', 'sms-templates'] as const,
    smsHistory: (params?: Record<string, unknown>) => ['admin', 'sms-history', params] as const,
    accounts: ['admin', 'accounts'] as const,
    balanceSheet: (params?: Record<string, unknown>) => ['admin', 'balance-sheet', params] as const,
    journalEntries: (params?: Record<string, unknown>) => ['admin', 'journal-entries', params] as const,
    transactions: (params?: Record<string, unknown>) => ['admin', 'transactions', params] as const,
    routers: ['admin', 'routers'] as const,
    routerDetail: (id: string | number) => ['admin', 'router', id] as const,
    routerSessions: (id: string | number) => ['admin', 'router-sessions', id] as const,
    ipPools: ['admin', 'ip-pools'] as const,
    packages: (params?: Record<string, unknown>) => ['admin', 'packages', params] as const,
    packageDetail: (id: string | number) => ['admin', 'package', id] as const,
    olts: (params?: Record<string, unknown>) => ['admin', 'olts', params] as const,
    oltDetail: (id: string | number) => ['admin', 'olt', id] as const,
    hotspots: (params?: Record<string, unknown>) => ['admin', 'hotspots', params] as const,
    inventoryItems: (params?: Record<string, unknown>) => ['admin', 'inventory-items', params] as const,
    inventoryPurchases: (params?: Record<string, unknown>) => ['admin', 'inventory-purchases', params] as const,
    reports: (type: string, params?: Record<string, unknown>) => ['admin', 'reports', type, params] as const,
    whatsappSettings: ['admin', 'whatsapp-settings'] as const,
    userAccess: ['admin', 'user-access'] as const,
  },
  employee: {
    dashboard: ['employee', 'dashboard'] as const,
    payslips: (params?: Record<string, unknown>) => ['employee', 'payslips', params] as const,
    payslipDetail: (id: string | number) => ['employee', 'payslip', id] as const,
    advanceSalary: (params?: Record<string, unknown>) => ['employee', 'advance-salary', params] as const,
    attendance: (params?: Record<string, unknown>) => ['employee', 'attendance', params] as const,
    tasks: (params?: Record<string, unknown>) => ['employee', 'tasks', params] as const,
  },
  platform: {
    dashboard: ['platform', 'dashboard'] as const,
    tenants: (params?: Record<string, unknown>) => ['platform', 'tenants', params] as const,
    tenantDetail: (id: string | number) => ['platform', 'tenant', id] as const,
    admins: (params?: Record<string, unknown>) => ['platform', 'admins', params] as const,
    revenue: (params?: Record<string, unknown>) => ['platform', 'revenue', params] as const,
    plugins: ['platform', 'plugins'] as const,
  },
};
