/** Human labels for engine action keys (operator UX, not snake_case). */
const LABELS: Record<string, string> = {
  run: 'Run',
  run_now: 'Run now',
  pause: 'Pause',
  resume: 'Resume',
  save: 'Save',
  publish: 'Publish',
  duplicate: 'Duplicate',
  enable: 'Enable',
  disable: 'Disable',
  test: 'Test',
  validate: 'Validate',
  simulate: 'Simulate',
  retry: 'Retry',
  retry_all: 'Retry all',
  configure: 'Configure',
  replay: 'Replay',
  export: 'Export',
  filter: 'Filter',
  use: 'Use template',
  clone: 'Clone',
  refresh: 'Refresh',
  provision: 'Provision',
  deprovision: 'Deprovision',
  reprovision: 'Reprovision',
  view: 'View',
  cancel: 'Cancel',
  prioritize: 'Prioritize',
  override: 'Override',
  start: 'Start',
  preview: 'Preview',
  edit: 'Edit',
  apply: 'Apply',
  ack: 'Acknowledge',
  unack: 'Undo ack',
  escalate: 'Escalate',
  suppress: 'Suppress',
  add: 'Add',
  remove: 'Remove',
  create: 'Create',
  end: 'End window',
  open: 'Open',
  resolve: 'Resolve',
  convert: 'Convert',
  approve: 'Approve',
  reject: 'Reject',
  verify: 'Verify',
  request_docs: 'Request docs',
  schedule: 'Schedule',
  complete: 'Complete',
  activate: 'Activate',
  suspend: 'Suspend',
  hold: 'Hold',
  release: 'Release',
  reactivate: 'Reactivate',
  archive: 'Archive',
  restore: 'Restore',
  migrate: 'Migrate',
  merge: 'Merge',
  transfer: 'Transfer',
  reschedule: 'Reschedule',
  assign: 'Assign',
  reassign: 'Reassign',
  complete_item: 'Mark done',
  return: 'Return',
  charge: 'Charge',
  waive: 'Waive',
  upload: 'Upload',
  capture: 'Capture',
  register: 'Register',
  pass: 'Pass QA',
  fail: 'Fail QA',
  post: 'Post',
  pay: 'Pay',
  match: 'Match',
  unmatch: 'Unmatch',
  lock: 'Lock',
  unlock: 'Unlock',
  switch: 'Switch',
  settle: 'Settle',
  recalculate: 'Recalculate',
  snooze: 'Snooze',
  log: 'Log activity',
  build: 'Build',
  launch: 'Launch',
  generate: 'Generate',
  summarize: 'Summarize',
  diagnose: 'Diagnose',
  ask: 'Ask',
  recommend: 'Recommend',
  send: 'Send',
  reply: 'Reply',
  update: 'Update',
  topup: 'Top up',
  issue: 'Issue invoice',
  revoke: 'Revoke',
  discover: 'Discover',
  backup: 'Backup',
  diff: 'Diff',
  rollback: 'Rollback',
  replace: 'Replace',
  relocate: 'Relocate',
  close: 'Close',
  resend: 'Resend',
  adjust: 'Adjust',
  delete: 'Delete',
  reset: 'Reset',
  rotate: 'Rotate',
  terminate: 'Terminate',
  unlock_user: 'Unlock',
  block: 'Block',
  writeoff: 'Write off',
  receive: 'Receive',
  claim: 'Claim',
  advance: 'Advance',
};

export function humanizeAction(action: string): string {
  if (LABELS[action]) return LABELS[action]!;
  return action.replaceAll('_', ' ');
}
