import type { NavItem } from './types';

/** Tenant admin + reseller sidebar — mirrors `sidebar.php` */
export const adminNavigation: NavItem[] = [
  // ── Dashboard ──────────────────────────────────────────────
  {
    id: 'dashboard',
    label: 'Dashboard',
    href: '/admin/dashboard',
    icon: 'LayoutDashboard',
    roles: ['admin', 'resellerAdmin'],
    hideWhenExpired: true,
  },

  // ── Operations ─────────────────────────────────────────────
  {
    id: 'areas',
    label: 'Service Areas',
    href: '/admin/areas',
    icon: 'MapPin',
    roles: ['admin', 'resellerAdmin'],
    permission: { menu: 'area', action: 'read' },
    section: 'Operations',
    hideWhenExpired: true,
  },
  {
    id: 'customers',
    label: 'Customers',
    icon: 'Users',
    roles: ['admin', 'resellerAdmin'],
    permission: { menu: 'customer', action: 'read' },
    section: 'Operations',
    hideWhenExpired: true,
    children: [
      { id: 'customers-all', label: 'All Customers', href: '/admin/customers' },
      { id: 'customers-expired', label: 'Expired Customers', href: '/admin/customers/expired' },
      { id: 'customers-free', label: 'Free User Requests', href: '/admin/customers/free-requests' },
      {
        id: 'customers-payments',
        label: 'Customers Payment',
        href: '/admin/customer-payments',
        permission: { menu: 'customer_payment', action: 'read' },
      },
    ],
  },
  {
    id: 'reports',
    label: 'Reports',
    icon: 'BarChart3',
    roles: ['admin', 'resellerAdmin'],
    permission: { menu: 'report', action: 'read' },
    section: 'Operations',
    hideWhenExpired: true,
    children: [
      { id: 'reports-btrc', label: 'BTRC Report', href: '/admin/reports/btrc' },
      { id: 'reports-otc', label: 'OTC Report', href: '/admin/reports/otc' },
    ],
  },
  {
    id: 'network',
    label: 'Network',
    icon: 'Share2',
    roles: ['admin', 'resellerAdmin'],
    section: 'Operations',
    hideWhenExpired: true,
    children: [
      { id: 'network-diagram', label: 'Network Diagram', href: '/admin/network/diagram' },
      { id: 'network-map', label: 'Network Map', href: '/admin/network/map' },
    ],
  },

  // ── HR ─────────────────────────────────────────────────────
  {
    id: 'hr',
    label: 'HR Management',
    icon: 'UserCog',
    roles: ['admin', 'resellerAdmin'],
    section: 'HR',
    hideWhenExpired: true,
    children: [
      { id: 'hr-employees', label: 'Staff List', href: '/admin/hr/employees', permission: { menu: 'employee', action: 'read' } },
      { id: 'hr-salaries', label: 'Salary Payments', href: '/admin/hr/salaries', permission: { menu: 'employee_payment', action: 'read' } },
      { id: 'hr-attendance', label: 'Attendance Tracking', href: '/admin/hr/attendance', permission: { menu: 'employee_attendance', action: 'read' } },
      { id: 'hr-accounts', label: 'Employee Accounts', href: '/admin/hr/accounts', permission: { menu: 'advance_salary', action: 'read' } },
      { id: 'hr-advance', label: 'Advance Salary', href: '/admin/hr/advance-salary', permission: { menu: 'advance_salary', action: 'read' } },
    ],
  },

  // ── Billing ────────────────────────────────────────────────
  {
    id: 'packages',
    label: 'Packages',
    href: '/admin/packages',
    icon: 'Package',
    roles: ['admin', 'resellerAdmin'],
    permission: { menu: 'packages', action: 'read' },
    section: 'Billing',
    hideWhenExpired: true,
  },
  {
    id: 'accounting',
    label: 'Accounting',
    icon: 'Calculator',
    roles: ['admin', 'resellerAdmin'],
    permission: { menu: 'accounting', action: 'read' },
    section: 'Billing',
    hideWhenExpired: true,
    children: [
      { id: 'acc-incomes', label: 'Incomes', href: '/admin/accounting/incomes' },
      { id: 'acc-expenses', label: 'Expenses', href: '/admin/accounting/expenses' },
      { id: 'acc-reports', label: 'Accounts Report', href: '/admin/accounting/reports' },
      { id: 'acc-coa', label: 'Chart of Accounts', href: '/admin/accounting/chart-of-accounts' },
      { id: 'acc-journal', label: 'Journal Entries', href: '/admin/accounting/journal-entries' },
      { id: 'acc-balance', label: 'Balance Sheet', href: '/admin/accounting/balance-sheet' },
    ],
  },
  {
    id: 'pop',
    label: 'POP',
    icon: 'Building2',
    roles: ['admin'],
    permission: { menu: 'Resellers', action: 'read' },
    section: 'Billing',
    hideWhenExpired: true,
    children: [
      { id: 'pop-list', label: 'POP Resellers', href: '/admin/pop/resellers' },
      { id: 'pop-packages-menu', label: 'Customer Packages', href: '/admin/pop-packages' },
      { id: 'pop-payments', label: 'Customer Payments', href: '/admin/customer-payments' },
      { id: 'pop-funding-menu', label: 'POP Funding', href: '/admin/pop/funding' },
      { id: 'pop-tx-menu', label: 'POP Transactions', href: '/admin/pop/transactions' },
    ],
  },
  {
    id: 'bandwidth-buy',
    label: 'Bandwidth Buy',
    icon: 'ArrowDownToLine',
    roles: ['admin', 'resellerAdmin'],
    section: 'Billing',
    hideWhenExpired: true,
    children: [
      { id: 'bw-buy-list', label: 'Buy List', href: '/admin/bandwidth/buy' },
      { id: 'bw-buy-items', label: 'Items', href: '/admin/bandwidth/buy/items' },
      { id: 'bw-buy-categories', label: 'Categories', href: '/admin/bandwidth/buy/categories' },
      { id: 'bw-buy-providers', label: 'Providers', href: '/admin/bandwidth/buy/providers' },
      { id: 'bw-buy-daily', label: 'Daily Bill', href: '/admin/bandwidth/daily-bill' },
    ],
  },
  {
    id: 'bandwidth-sell',
    label: 'Bandwidth Sell',
    icon: 'ArrowUpFromLine',
    roles: ['admin', 'resellerAdmin'],
    section: 'Billing',
    hideWhenExpired: true,
    children: [
      { id: 'bw-sell-list', label: 'Sell List', href: '/admin/bandwidth/sell' },
      { id: 'bw-sell-clients', label: 'Clients', href: '/admin/bandwidth/sell/clients' },
      { id: 'bw-sell-invoices', label: 'Invoices', href: '/admin/bandwidth/sell/invoices' },
    ],
  },
  {
    id: 'self-recharge',
    label: 'Self Recharge',
    href: '/admin/subscription',
    icon: 'Zap',
    roles: ['admin'],
    section: 'Billing',
    expiredOnly: true,
  },
  {
    id: 'my-payment-admin',
    label: 'My Payment',
    href: '/admin/payment',
    icon: 'Banknote',
    roles: ['admin'],
    section: 'Billing',
    expiredOnly: true,
  },

  // ── Inventory ──────────────────────────────────────────────
  {
    id: 'inventory',
    label: 'Inventory',
    icon: 'Warehouse',
    roles: ['admin', 'resellerAdmin'],
    permission: { menu: 'inventory', action: 'read' },
    section: 'Inventory',
    hideWhenExpired: true,
    children: [
      { id: 'inv-items', label: 'Items', href: '/admin/inventory/items' },
      { id: 'inv-categories', label: 'Categories', href: '/admin/inventory/categories' },
      { id: 'inv-stock', label: 'Stock', href: '/admin/inventory/stock' },
      { id: 'inv-units', label: 'Units', href: '/admin/inventory/units' },
      { id: 'inv-locations', label: 'Locations', href: '/admin/inventory/locations' },
    ],
  },
  {
    id: 'purchase',
    label: 'Purchase',
    icon: 'ShoppingCart',
    roles: ['admin', 'resellerAdmin'],
    permission: { menu: 'purchase', action: 'read' },
    section: 'Inventory',
    hideWhenExpired: true,
    children: [
      { id: 'purchase-bills', label: 'Bills', href: '/admin/purchase/bills' },
      { id: 'purchase-requisitions', label: 'Requisitions', href: '/admin/purchase/requisitions' },
      { id: 'purchase-vendors', label: 'Vendors', href: '/admin/purchase/vendors' },
    ],
  },

  // ── Network ────────────────────────────────────────────────
  {
    id: 'hotspot',
    label: 'Hotspot',
    icon: 'Wifi',
    roles: ['admin', 'resellerAdmin'],
    permission: { menu: 'hotspot', action: 'read' },
    section: 'Network',
    hideWhenExpired: true,
    children: [
      { id: 'hotspot-dashboard', label: 'Dashboard', href: '/admin/hotspot/dashboard' },
      { id: 'hotspot-packages', label: 'Packages', href: '/admin/hotspot/packages' },
      { id: 'hotspot-users', label: 'Users', href: '/admin/hotspot/users' },
      { id: 'hotspot-reports', label: 'Reports', href: '/admin/hotspot/reports' },
    ],
  },
  {
    id: 'olt',
    label: 'OLT',
    href: '/admin/olt',
    icon: 'Network',
    roles: ['admin', 'resellerAdmin'],
    permission: { menu: 'olt', action: 'read' },
    section: 'Network',
    hideWhenExpired: true,
  },
  {
    id: 'routers',
    label: 'Routers',
    href: '/admin/routers',
    icon: 'Router',
    roles: ['admin', 'resellerAdmin'],
    permission: { menu: 'router', action: 'read' },
    section: 'Network',
    hideWhenExpired: true,
  },
  {
    id: 'ip-pools',
    label: 'IP Pools',
    href: '/admin/ip-pools',
    icon: 'Globe2',
    roles: ['admin', 'resellerAdmin'],
    permission: { menu: 'ip_pool', action: 'read' },
    section: 'Network',
    hideWhenExpired: true,
  },

  // ── Comms ──────────────────────────────────────────────────
  {
    id: 'sms',
    label: 'SMS',
    href: '/admin/sms',
    icon: 'MessageSquare',
    roles: ['admin', 'resellerAdmin'],
    permission: { menu: 'sms', action: 'read' },
    section: 'Comms',
    hideWhenExpired: true,
  },
  {
    id: 'sms-templates',
    label: 'SMS Templates',
    href: '/admin/sms-templates',
    icon: 'FileText',
    roles: ['admin', 'resellerAdmin'],
    permission: { menu: 'sms_template', action: 'read' },
    section: 'Comms',
    hideWhenExpired: true,
  },
  {
    id: 'voice-sms',
    label: 'Voice SMS',
    href: '/admin/voice-sms',
    icon: 'Phone',
    roles: ['admin', 'resellerAdmin'],
    permission: { menu: 'voice_sms', action: 'read' },
    section: 'Comms',
    hideWhenExpired: true,
  },
  {
    id: 'whatsapp',
    label: 'WhatsApp Business',
    icon: 'MessageCircle',
    roles: ['admin', 'resellerAdmin'],
    permission: { menu: 'whatsapp', action: 'read' },
    section: 'Comms',
    hideWhenExpired: true,
    children: [
      { id: 'wa-inbox', label: 'Inbox', href: '/admin/whatsapp/inbox' },
      { id: 'wa-templates', label: 'Templates', href: '/admin/whatsapp/templates' },
      { id: 'wa-log', label: 'Message Log', href: '/admin/whatsapp/message-log' },
      { id: 'wa-optins', label: 'Opt-ins', href: '/admin/whatsapp/opt-ins' },
      { id: 'wa-campaigns', label: 'Campaigns', href: '/admin/whatsapp/campaigns' },
      { id: 'wa-settings', label: 'Settings', href: '/admin/whatsapp/settings' },
    ],
  },

  // ── Engagement ─────────────────────────────────────────────
  {
    id: 'rewards',
    label: 'Rewards',
    href: '/admin/rewards',
    icon: 'Gift',
    roles: ['admin', 'resellerAdmin'],
    permission: { menu: 'reward', action: 'read' },
    section: 'Engagement',
    hideWhenExpired: true,
  },
  {
    id: 'support',
    label: 'Support Tickets',
    href: '/admin/support',
    icon: 'LifeBuoy',
    roles: ['admin', 'resellerAdmin'],
    permission: { menu: 'support', action: 'read' },
    section: 'Engagement',
    hideWhenExpired: true,
  },

  // ── System ─────────────────────────────────────────────────
  {
    id: 'wallet',
    label: 'Wallet',
    href: '/admin/wallet',
    icon: 'Wallet',
    roles: ['admin', 'resellerAdmin'],
    permission: { menu: 'wallet', action: 'read' },
    section: 'System',
    hideWhenExpired: true,
  },
  {
    id: 'subscription',
    label: 'Subscription',
    href: '/admin/subscription',
    icon: 'CalendarCheck',
    roles: ['admin'],
    permission: { menu: 'subscription', action: 'read' },
    section: 'System',
    hideWhenExpired: true,
  },
  {
    id: 'payment',
    label: 'Payment',
    href: '/admin/payment',
    icon: 'CreditCard',
    roles: ['admin'],
    permission: { menu: 'payment', action: 'read' },
    section: 'System',
    hideWhenExpired: true,
  },
  {
    id: 'recycle-bin',
    label: 'Recycle Bin',
    href: '/admin/recycle-bin',
    icon: 'Trash2',
    roles: ['admin', 'resellerAdmin'],
    permission: { menu: 'recycle_bin', action: 'read' },
    section: 'System',
    hideWhenExpired: true,
  },
  {
    id: 'user-access',
    label: 'User Access Management',
    href: '/admin/user-access',
    icon: 'Shield',
    roles: ['admin'],
    permission: { menu: 'user_access', action: 'read' },
    section: 'System',
    hideWhenExpired: true,
  },
  {
    id: 'settings',
    label: 'Settings',
    href: '/admin/settings',
    icon: 'Settings',
    roles: ['admin', 'resellerAdmin'],
    permission: { menu: 'software_settings', action: 'read' },
    section: 'System',
    hideWhenExpired: true,
  },
  {
    id: 'theme-studio',
    label: 'Theme Studio',
    href: '/admin/theme-studio',
    icon: 'Palette',
    roles: ['admin'],
    section: 'System',
    hideWhenExpired: true,
  },
  {
    id: 'profile',
    label: 'Profile',
    href: '/admin/profile',
    icon: 'User',
    roles: ['admin', 'resellerAdmin'],
    section: 'System',
    hideWhenExpired: true,
  },
];
