import type { NavItem } from './types';

/** Tenant admin + reseller sidebar — mirrors `sidebar.php` */
export const adminNavigation: NavItem[] = [
  // ── Dashboard ──────────────────────────────────────────────
  {
    id: 'dashboard',
    label: 'Dashboard',
    href: '/admin/dashboard',
    icon: 'LayoutDashboard',
    roles: ['admin', 'resellerAdmin'],
    hideWhenExpired: true,
  },
  {
    id: 'hierarchy',
    label: 'Hierarchy',
    href: '/admin/hierarchy',
    icon: 'Network',
    roles: ['admin', 'resellerAdmin'],
    section: 'Operations',
    hideWhenExpired: true,
  },

  // ── Operations ─────────────────────────────────────────────
  {
    id: 'areas',
    label: 'Service Areas',
    href: '/admin/areas',
    icon: 'MapPin',
    roles: ['admin', 'resellerAdmin'],
    permission: { menu: 'area', action: 'read' },
    section: 'Operations',
    hideWhenExpired: true,
  },
  {
    id: 'customers',
    label: 'Customers',
    icon: 'Users',
    roles: ['admin', 'resellerAdmin'],
    permission: { menu: 'customer', action: 'read' },
    section: 'Operations',
    hideWhenExpired: true,
    children: [
      { id: 'customers-all', label: 'All Customers', href: '/admin/customers' },
      { id: 'customers-expired', label: 'Expired Customers', href: '/admin/customers/expired' },
      { id: 'customers-inactive', label: 'Inactive Customers', href: '/admin/customers/inactive' },
      { id: 'customers-groups', label: 'Customer Groups', href: '/admin/customers/groups' },
      { id: 'customers-free', label: 'Free User Requests', href: '/admin/customers/free-requests' },
      {
        id: 'customers-payments',
        label: 'Customers Payment',
        href: '/admin/customer-payments',
        permission: { menu: 'customer_payment', action: 'read' },
      },
    ],
  },
  {
    id: 'reports',
    label: 'Reports',
    icon: 'BarChart3',
    roles: ['admin', 'resellerAdmin'],
    permission: { menu: 'reports', action: 'read' },
    section: 'Operations',
    hideWhenExpired: true,
    children: [
      { id: 'reports-btrc', label: 'BTRC Report', href: '/admin/reports/btrc' },
      { id: 'reports-otc', label: 'OTC Report', href: '/admin/reports/otc' },
      { id: 'reports-usage', label: 'Bandwidth Usage', href: '/admin/reports/usage' },
      { id: 'reports-collections-map', label: 'Collections Map', href: '/admin/reports/collections-map' },
    ],
  },
  {
    id: 'network',
    label: 'Network',
    icon: 'Share2',
    roles: ['admin', 'resellerAdmin'],
    section: 'Operations',
    hideWhenExpired: true,
    children: [
      { id: 'network-diagram', label: 'Network Diagram', href: '/admin/network/diagram' },
      { id: 'network-map', label: 'Network Map', href: '/admin/network/map' },
      { id: 'network-outages', label: 'Outages', href: '/admin/network/outages' },
      { id: 'network-pon', label: 'PON Map', href: '/admin/network/pon' },
      { id: 'network-cgnat', label: 'CGNAT', href: '/admin/network/cgnat' },
      { id: 'network-netflow', label: 'NetFlow', href: '/admin/network/netflow' },
      { id: 'network-ipoe', label: 'IPoE', href: '/admin/network/ipoe' },
    ],
  },
  {
    id: 'jobs',
    label: 'Work Orders',
    href: '/admin/jobs',
    icon: 'ClipboardList',
    roles: ['admin', 'resellerAdmin'],
    section: 'Operations',
    hideWhenExpired: true,
  },
  {
    id: 'leads',
    label: 'Leads',
    href: '/admin/leads',
    icon: 'Target',
    roles: ['admin', 'resellerAdmin'],
    section: 'Operations',
    hideWhenExpired: true,
  },

  // ── HR ─────────────────────────────────────────────────────
  {
    id: 'hr',
    label: 'HR Management',
    icon: 'UserCog',
    roles: ['admin', 'resellerAdmin'],
    section: 'HR',
    hideWhenExpired: true,
    children: [
      { id: 'hr-employees', label: 'Staff List', href: '/admin/hr/employees', permission: { menu: 'employee', action: 'read' } },
      { id: 'hr-salaries', label: 'Salary Payments', href: '/admin/hr/salaries', permission: { menu: 'employee_payment', action: 'read' } },
      { id: 'hr-attendance', label: 'Attendance Tracking', href: '/admin/hr/attendance', permission: { menu: 'employee_attendance', action: 'read' } },
      { id: 'hr-accounts', label: 'Employee Accounts', href: '/admin/hr/accounts', permission: { menu: 'advance_salary', action: 'read' } },
      { id: 'hr-advance', label: 'Advance Salary', href: '/admin/hr/advance-salary', permission: { menu: 'advance_salary', action: 'read' } },
    ],
  },

  // ── Billing ────────────────────────────────────────────────
  {
    id: 'packages',
    label: 'Packages',
    href: '/admin/packages',
    icon: 'Package',
    roles: ['admin', 'resellerAdmin'],
    permission: { menu: 'packages', action: 'read' },
    section: 'Billing',
    hideWhenExpired: true,
  },
  {
    id: 'billing',
    label: 'Billing',
    icon: 'Receipt',
    roles: ['admin', 'resellerAdmin'],
    section: 'Billing',
    hideWhenExpired: true,
    children: [
      { id: 'billing-invoices', label: 'Invoices', href: '/admin/invoices' },
      { id: 'billing-policies', label: 'Policies', href: '/admin/billing/policies' },
      { id: 'billing-tax', label: 'Tax / VAT', href: '/admin/billing/tax' },
      { id: 'billing-dunning', label: 'Dunning', href: '/admin/billing/dunning' },
      { id: 'billing-proration', label: 'Proration', href: '/admin/billing/proration' },
      { id: 'billing-deposits', label: 'Deposits / OTC', href: '/admin/billing/deposits' },
    ],
  },
  {
    id: 'collections',
    label: 'Collections',
    icon: 'HandCoins',
    roles: ['admin', 'resellerAdmin'],
    section: 'Billing',
    hideWhenExpired: true,
    children: [
      { id: 'collections-reminders', label: 'Reminders', href: '/admin/collections/reminders' },
      { id: 'collections-cashbook', label: 'Cash Book', href: '/admin/collections/cashbook' },
      { id: 'collections-credits', label: 'Credit Notes', href: '/admin/payments/credits' },
      { id: 'collections-reconcile', label: 'Reconcile', href: '/admin/payments/reconcile' },
    ],
  },
  {
    id: 'addons',
    label: 'Addons',
    href: '/admin/addons',
    icon: 'Layers',
    roles: ['admin', 'resellerAdmin'],
    section: 'Billing',
    hideWhenExpired: true,
  },
  {
    id: 'services',
    label: 'Services',
    icon: 'Boxes',
    roles: ['admin', 'resellerAdmin'],
    section: 'Billing',
    hideWhenExpired: true,
    children: [
      { id: 'services-types', label: 'Service Types', href: '/admin/services' },
      { id: 'services-mobile', label: 'Mobile Plans', href: '/admin/services/mobile' },
    ],
  },
  {
    id: 'accounting',
    label: 'Accounting',
    icon: 'Calculator',
    roles: ['admin', 'resellerAdmin'],
    permission: { menu: 'accounting', action: 'read' },
    section: 'Billing',
    hideWhenExpired: true,
    children: [
      { id: 'acc-incomes', label: 'Incomes', href: '/admin/accounting/incomes' },
      { id: 'acc-expenses', label: 'Expenses', href: '/admin/accounting/expenses' },
      { id: 'acc-reports', label: 'Accounts Report', href: '/admin/accounting/reports' },
      { id: 'acc-coa', label: 'Chart of Accounts', href: '/admin/accounting/chart-of-accounts' },
      { id: 'acc-journal', label: 'Journal Entries', href: '/admin/accounting/journal-entries' },
      { id: 'acc-balance', label: 'Balance Sheet', href: '/admin/accounting/balance-sheet' },
    ],
  },
  {
    id: 'pop',
    label: 'POP',
    icon: 'Building2',
    roles: ['admin'],
    permission: { menu: 'Resellers', action: 'read' },
    section: 'Billing',
    hideWhenExpired: true,
    children: [
      { id: 'pop-list', label: 'POP Resellers', href: '/admin/pop/resellers' },
      { id: 'pop-packages-menu', label: 'Customer Packages', href: '/admin/pop-packages' },
      { id: 'pop-payments', label: 'Customer Payments', href: '/admin/customer-payments' },
      { id: 'pop-funding-menu', label: 'POP Funding', href: '/admin/pop/funding' },
      { id: 'pop-tx-menu', label: 'POP Transactions', href: '/admin/pop/transactions' },
      { id: 'pop-commissions', label: 'Commissions', href: '/admin/pop/commissions' },
      { id: 'pop-package-profit', label: 'Package Profit', href: '/admin/pop/package-profit' },
    ],
  },
  {
    id: 'dealers',
    label: 'Dealers',
    href: '/admin/dealers',
    icon: 'Store',
    roles: ['admin'],
    section: 'Billing',
    hideWhenExpired: true,
  },
  {
    id: 'bandwidth-buy',
    label: 'Bandwidth Buy',
    icon: 'ArrowDownToLine',
    roles: ['admin', 'resellerAdmin'],
    section: 'Billing',
    hideWhenExpired: true,
    children: [
      { id: 'bw-buy-list', label: 'Buy List', href: '/admin/bandwidth/buy' },
      { id: 'bw-buy-items', label: 'Items', href: '/admin/bandwidth/buy/items' },
      { id: 'bw-buy-categories', label: 'Categories', href: '/admin/bandwidth/buy/categories' },
      { id: 'bw-buy-providers', label: 'Providers', href: '/admin/bandwidth/buy/providers' },
      { id: 'bw-buy-bills', label: 'Purchase Bills', href: '/admin/bandwidth/buy/bills' },
      { id: 'bw-buy-daily', label: 'Daily Bill', href: '/admin/bandwidth/daily-bill' },
    ],
  },
  {
    id: 'bandwidth-sell',
    label: 'Bandwidth Sell',
    icon: 'ArrowUpFromLine',
    roles: ['admin', 'resellerAdmin'],
    section: 'Billing',
    hideWhenExpired: true,
    children: [
      { id: 'bw-sell-list', label: 'Sell List', href: '/admin/bandwidth/sell' },
      { id: 'bw-sell-clients', label: 'Clients', href: '/admin/bandwidth/sell/clients' },
      { id: 'bw-sell-invoices', label: 'Invoices', href: '/admin/bandwidth/sell/invoices' },
    ],
  },
  {
    id: 'self-recharge',
    label: 'Self Recharge',
    href: '/admin/subscription',
    icon: 'Zap',
    roles: ['admin'],
    section: 'Billing',
    expiredOnly: true,
  },
  {
    id: 'my-payment-admin',
    label: 'My Payment',
    href: '/admin/payment',
    icon: 'Banknote',
    roles: ['admin'],
    section: 'Billing',
    expiredOnly: true,
  },

  // ── Inventory ──────────────────────────────────────────────
  {
    id: 'inventory',
    label: 'Inventory',
    icon: 'Warehouse',
    roles: ['admin', 'resellerAdmin'],
    permission: { menu: 'inventory_purchess', action: 'read' },
    section: 'Inventory',
    hideWhenExpired: true,
    children: [
      { id: 'inv-items', label: 'Items', href: '/admin/inventory/items' },
      { id: 'inv-categories', label: 'Categories', href: '/admin/inventory/categories' },
      { id: 'inv-stock', label: 'Stock', href: '/admin/inventory/stock' },
      { id: 'inv-units', label: 'Units', href: '/admin/inventory/units' },
      { id: 'inv-locations', label: 'Locations', href: '/admin/inventory/locations' },
      { id: 'inv-assign', label: 'CPE Assign', href: '/admin/inventory/assign' },
      { id: 'inv-transfers', label: 'Transfers', href: '/admin/inventory/transfers' },
    ],
  },
  {
    id: 'purchase',
    label: 'Purchase',
    icon: 'ShoppingCart',
    roles: ['admin', 'resellerAdmin'],
    permission: { menu: 'inventory_purchess', action: 'read' },
    section: 'Inventory',
    hideWhenExpired: true,
    children: [
      { id: 'purchase-bills', label: 'Bills', href: '/admin/purchase/bills' },
      { id: 'purchase-requisitions', label: 'Requisitions', href: '/admin/purchase/requisitions' },
      { id: 'purchase-vendors', label: 'Vendors', href: '/admin/purchase/vendors' },
    ],
  },

  // ── Network ────────────────────────────────────────────────
  {
    id: 'hotspot',
    label: 'Hotspot',
    icon: 'Wifi',
    roles: ['admin', 'resellerAdmin'],
    permission: { menu: 'hotspot', action: 'read' },
    section: 'Network',
    hideWhenExpired: true,
    children: [
      { id: 'hotspot-hub', label: 'Hotspot Hub', href: '/admin/hotspot' },
      { id: 'hotspot-dashboard', label: 'Dashboard', href: '/admin/hotspot/dashboard' },
      { id: 'hotspot-packages', label: 'Packages', href: '/admin/hotspot/packages' },
      { id: 'hotspot-users', label: 'Users', href: '/admin/hotspot/users' },
      { id: 'hotspot-vouchers', label: 'Vouchers', href: '/admin/hotspot/vouchers' },
      { id: 'hotspot-walled', label: 'Walled Garden', href: '/admin/hotspot/walled-garden' },
      { id: 'hotspot-reports', label: 'Reports', href: '/admin/hotspot/reports' },
    ],
  },
  {
    id: 'olt',
    label: 'OLT',
    icon: 'Network',
    roles: ['admin', 'resellerAdmin'],
    permission: { menu: 'olt', action: 'read' },
    section: 'Network',
    hideWhenExpired: true,
    children: [
      { id: 'olt-list', label: 'OLT List', href: '/admin/olt' },
      { id: 'olt-vendors', label: 'Vendors', href: '/admin/olt/vendors' },
      { id: 'olt-onus', label: 'ONUs (sample)', href: '/admin/olt/olt_01/onus' },
    ],
  },
  {
    id: 'routers',
    label: 'Routers',
    href: '/admin/routers',
    icon: 'Router',
    roles: ['admin', 'resellerAdmin'],
    permission: { menu: 'routers', action: 'read' },
    section: 'Network',
    hideWhenExpired: true,
  },
  {
    id: 'radius',
    label: 'RADIUS',
    href: '/admin/radius',
    icon: 'Radio',
    roles: ['admin', 'resellerAdmin'],
    section: 'Network',
    hideWhenExpired: true,
  },
  {
    id: 'ip-pools',
    label: 'IP Pools',
    href: '/admin/ip-pools',
    icon: 'Globe2',
    roles: ['admin', 'resellerAdmin'],
    permission: { menu: 'routers', action: 'read' },
    section: 'Network',
    hideWhenExpired: true,
  },
  {
    id: 'ipam',
    label: 'IPAM',
    href: '/admin/ipam',
    icon: 'Binary',
    roles: ['admin', 'resellerAdmin'],
    section: 'Network',
    hideWhenExpired: true,
  },
  {
    id: 'acs',
    label: 'ACS / TR-069',
    href: '/admin/acs',
    icon: 'Cable',
    roles: ['admin'],
    section: 'Network',
    hideWhenExpired: true,
  },
  {
    id: 'noc',
    label: 'NOC Hooks',
    href: '/admin/noc',
    icon: 'BellRing',
    roles: ['admin'],
    section: 'Network',
    hideWhenExpired: true,
  },
  {
    id: 'vpn',
    label: 'VPN',
    href: '/admin/vpn',
    icon: 'Shield',
    roles: ['admin'],
    section: 'Network',
    hideWhenExpired: true,
  },
  {
    id: 'bandwidth-sla',
    label: 'Bandwidth SLA',
    href: '/admin/bandwidth/sla',
    icon: 'Gauge',
    roles: ['admin', 'resellerAdmin'],
    section: 'Network',
    hideWhenExpired: true,
  },

  // ── Comms ──────────────────────────────────────────────────
  {
    id: 'sms',
    label: 'SMS',
    href: '/admin/sms',
    icon: 'MessageSquare',
    roles: ['admin', 'resellerAdmin'],
    permission: { menu: 'sms_message', action: 'read' },
    section: 'Comms',
    hideWhenExpired: true,
  },
  {
    id: 'sms-templates',
    label: 'SMS Templates',
    href: '/admin/sms-templates',
    icon: 'FileText',
    roles: ['admin', 'resellerAdmin'],
    permission: { menu: 'sms_message', action: 'read' },
    section: 'Comms',
    hideWhenExpired: true,
  },
  {
    id: 'voice-sms',
    label: 'Voice SMS',
    href: '/admin/voice-sms',
    icon: 'Phone',
    roles: ['admin', 'resellerAdmin'],
    permission: { menu: 'sms_message', action: 'read' },
    section: 'Comms',
    hideWhenExpired: true,
  },
  {
    id: 'whatsapp',
    label: 'WhatsApp Business',
    icon: 'MessageCircle',
    roles: ['admin', 'resellerAdmin'],
    permission: { menu: 'whatsapp_business', action: 'read' },
    section: 'Comms',
    hideWhenExpired: true,
    children: [
      { id: 'wa-inbox', label: 'Inbox', href: '/admin/whatsapp/inbox' },
      { id: 'wa-templates', label: 'Templates', href: '/admin/whatsapp/templates' },
      { id: 'wa-log', label: 'Message Log', href: '/admin/whatsapp/message-log' },
      { id: 'wa-optins', label: 'Opt-ins', href: '/admin/whatsapp/opt-ins' },
      { id: 'wa-campaigns', label: 'Campaigns', href: '/admin/whatsapp/campaigns' },
      { id: 'wa-settings', label: 'Settings', href: '/admin/whatsapp/settings' },
    ],
  },

  // ── Engagement ─────────────────────────────────────────────
  {
    id: 'rewards',
    label: 'Rewards',
    icon: 'Gift',
    roles: ['admin', 'resellerAdmin'],
    permission: { menu: 'referral', action: 'read' },
    section: 'Engagement',
    hideWhenExpired: true,
    children: [
      { id: 'rewards-home', label: 'Rewards', href: '/admin/rewards' },
      { id: 'rewards-analytics', label: 'Referral Analytics', href: '/admin/rewards/analytics' },
    ],
  },
  {
    id: 'announcements',
    label: 'Announcements',
    href: '/admin/announcements',
    icon: 'Megaphone',
    roles: ['admin', 'resellerAdmin'],
    section: 'Engagement',
    hideWhenExpired: true,
  },
  {
    id: 'support',
    label: 'Support Tickets',
    href: '/admin/support',
    icon: 'LifeBuoy',
    roles: ['admin', 'resellerAdmin'],
    permission: { menu: 'support_ticket', action: 'read' },
    section: 'Engagement',
    hideWhenExpired: true,
  },
  {
    id: 'usage-alerts',
    label: 'Usage Alerts',
    href: '/admin/notifications/usage-alerts',
    icon: 'Bell',
    roles: ['admin', 'resellerAdmin'],
    section: 'Engagement',
    hideWhenExpired: true,
  },
  {
    id: 'fraud',
    label: 'Fraud',
    href: '/admin/fraud',
    icon: 'ShieldAlert',
    roles: ['admin'],
    section: 'Engagement',
    hideWhenExpired: true,
  },
  {
    id: 'contracts',
    label: 'Contracts',
    href: '/admin/contracts',
    icon: 'FileText',
    roles: ['admin'],
    section: 'Engagement',
    hideWhenExpired: true,
  },
  {
    id: 'news-manage',
    label: 'News & Notices',
    href: '/admin/news',
    icon: 'Newspaper',
    roles: ['admin', 'resellerAdmin'],
    section: 'Engagement',
    hideWhenExpired: true,
  },
  {
    id: 'ai-chat',
    label: 'AI Chat',
    href: '/admin/ai-chat',
    icon: 'Bot',
    roles: ['admin'],
    permission: { menu: 'ai_chat', action: 'chat' },
    section: 'Engagement',
    hideWhenExpired: true,
  },
  {
    id: 'product-showcase',
    label: 'Product Showcase',
    href: '/admin/product-showcase',
    icon: 'Clapperboard',
    roles: ['admin'],
    section: 'Engagement',
    hideWhenExpired: true,
  },

  // ── System ─────────────────────────────────────────────────
  {
    id: 'compliance',
    label: 'Compliance',
    icon: 'Scale',
    roles: ['admin'],
    section: 'System',
    hideWhenExpired: true,
    children: [
      { id: 'compliance-ip-logs', label: 'IP / NAT Logs', href: '/admin/compliance/ip-logs' },
    ],
  },
  {
    id: 'developers',
    label: 'Developers',
    href: '/admin/developers',
    icon: 'Code2',
    roles: ['admin'],
    section: 'System',
    hideWhenExpired: true,
  },
  {
    id: 'branding',
    label: 'Branding',
    href: '/admin/branding',
    icon: 'Paintbrush',
    roles: ['admin'],
    section: 'System',
    hideWhenExpired: true,
  },
  {
    id: 'backup',
    label: 'Backup',
    href: '/admin/backup',
    icon: 'HardDrive',
    roles: ['admin'],
    section: 'System',
    hideWhenExpired: true,
  },
  {
    id: 'wallet',
    label: 'Wallet',
    href: '/admin/wallet',
    icon: 'Wallet',
    roles: ['admin', 'resellerAdmin'],
    section: 'System',
    hideWhenExpired: true,
  },
  {
    id: 'subscription',
    label: 'Subscription',
    href: '/admin/subscription',
    icon: 'CalendarCheck',
    roles: ['admin'],
    permission: { menu: 'subscription', action: 'read' },
    section: 'System',
    hideWhenExpired: true,
  },
  {
    id: 'payment',
    label: 'Payment',
    href: '/admin/payment',
    icon: 'CreditCard',
    roles: ['admin'],
    permission: { menu: 'payment', action: 'read' },
    section: 'System',
    hideWhenExpired: true,
  },
  {
    id: 'payment-gateways',
    label: 'Payment Gateways',
    href: '/admin/payment-gateways',
    icon: 'Landmark',
    roles: ['admin'],
    permission: { menu: 'payment', action: 'read' },
    section: 'System',
    hideWhenExpired: true,
  },
  {
    id: 'movie-servers',
    label: 'Movie Servers',
    href: '/admin/movie-servers',
    icon: 'Film',
    roles: ['admin'],
    section: 'System',
    hideWhenExpired: true,
  },
  {
    id: 'corporate-queues',
    label: 'Corporate Queues',
    href: '/admin/corporate/queues',
    icon: 'ListOrdered',
    roles: ['admin'],
    permission: { menu: 'customer', action: 'read' },
    section: 'System',
    hideWhenExpired: true,
  },
  {
    id: 'audit-logs',
    label: 'Audit Logs',
    href: '/admin/audit-logs',
    icon: 'ScrollText',
    roles: ['admin'],
    section: 'System',
    hideWhenExpired: true,
  },
  {
    id: 'recycle-bin',
    label: 'Recycle Bin',
    href: '/admin/recycle-bin',
    icon: 'Trash2',
    roles: ['admin', 'resellerAdmin'],
    permission: { menu: 'recycle_bin', action: 'read' },
    section: 'System',
    hideWhenExpired: true,
  },
  {
    id: 'user-access',
    label: 'User Access Management',
    href: '/admin/user-access',
    icon: 'Shield',
    roles: ['admin'],
    permission: { menu: 'user_access', action: 'read' },
    section: 'System',
    hideWhenExpired: true,
  },
  {
    id: 'sidebar-pins',
    label: 'Sidebar Pins',
    href: '/admin/sidebar-pins',
    icon: 'Pin',
    roles: ['admin', 'resellerAdmin'],
    section: 'System',
    hideWhenExpired: true,
  },
  {
    id: 'settings',
    label: 'Settings',
    href: '/admin/settings',
    icon: 'Settings',
    roles: ['admin', 'resellerAdmin'],
    permission: { menu: 'software_settings', action: 'read' },
    section: 'System',
    hideWhenExpired: true,
  },
  {
    id: 'theme-studio',
    label: 'Theme Studio',
    href: '/admin/theme-studio',
    icon: 'Palette',
    roles: ['admin'],
    section: 'System',
    hideWhenExpired: true,
  },
  {
    id: 'profile',
    label: 'Profile',
    href: '/admin/profile',
    icon: 'User',
    roles: ['admin', 'resellerAdmin'],
    section: 'System',
    hideWhenExpired: true,
  },
];
