import type { NavItem } from './types';

export const platformNavigation: NavItem[] = [
  {
    id: 'platform-dashboard',
    label: 'Dashboard',
    href: '/platform/dashboard',
    icon: 'LayoutDashboard',
    roles: ['super_admin'],
    section: 'System',
  },
  {
    id: 'platform-tenants',
    label: 'Tenants',
    href: '/platform/tenants',
    icon: 'Globe',
    roles: ['super_admin'],
    section: 'System',
  },
  {
    id: 'platform-hierarchy',
    label: 'Hierarchy',
    href: '/platform/hierarchy',
    icon: 'Network',
    roles: ['super_admin'],
    section: 'System',
  },
  {
    id: 'platform-admins',
    label: 'Admins',
    href: '/platform/admins',
    icon: 'ShieldCheck',
    roles: ['super_admin'],
  },
  {
    id: 'platform-revenue',
    label: 'Revenue',
    href: '/platform/revenue',
    icon: 'TrendingUp',
    roles: ['super_admin'],
  },
  {
    id: 'platform-contacts',
    label: 'Contacts',
    href: '/platform/contacts',
    icon: 'Contact',
    roles: ['super_admin'],
  },
  {
    id: 'platform-showcase',
    label: 'Product Showcase',
    href: '/platform/showcase',
    icon: 'Sparkles',
    roles: ['super_admin'],
  },
  {
    id: 'platform-plugins',
    label: 'Plugins & Addons',
    href: '/platform/plugins',
    icon: 'Puzzle',
    roles: ['super_admin'],
  },
  {
    id: 'platform-file-manager',
    label: 'File Manager',
    href: '/platform/file-manager',
    icon: 'FolderTree',
    roles: ['super_admin'],
  },
  {
    id: 'platform-support',
    label: 'Support Tickets',
    href: '/platform/support-tickets',
    icon: 'Ticket',
    roles: ['super_admin'],
  },
  {
    id: 'platform-user-access',
    label: 'User Access Management',
    href: '/platform/user-access',
    icon: 'UserLock',
    roles: ['super_admin'],
  },
  {
    id: 'platform-settings',
    label: 'Software Settings',
    href: '/platform/settings/software',
    icon: 'Settings',
    roles: ['super_admin'],
  },
  {
    id: 'platform-redis',
    label: 'Redis & Logs',
    href: '/platform/redis-logs',
    icon: 'Database',
    roles: ['super_admin'],
  },
  {
    id: 'platform-maintenance',
    label: 'Maintenance Mode',
    href: '/platform/maintenance',
    icon: 'Wrench',
    roles: ['super_admin'],
  },
];
